import { useState } from "react";
import { Button, Input, Modal, Switch, toast } from "@heroui/react";
import { Database, Pencil, Plus, Trash2, X } from "lucide-react";
import { actions, useAppStore } from "../../store";
import type { HTTPSource } from "../../types";

const blank=():HTTPSource=>({id:"",name:"",url:"",enabled:true,nodeCount:0});

export function SourcesPage(){
  const sources=useAppStore(state=>state.sources); const [editing,setEditing]=useState<HTTPSource>(); const [error,setError]=useState("");
  const save=async()=>{if(!editing)return;if(!editing.name.trim()){setError("请输入数据源名称");return;}if(!/^https?:\/\//i.test(editing.url)){setError("URL 必须以 http:// 或 https:// 开头");return;}const value={...editing,id:editing.id||`source-${Date.now()}`};const next=sources.some(item=>item.id===value.id)?sources.map(item=>item.id===value.id?value:item):[...sources,value];await actions.saveSources(next);setEditing(undefined);toast.success("数据源已保存");};
  const remove=async(id:string)=>{await actions.saveSources(sources.filter(item=>item.id!==id));toast.success("数据源已删除");};
  const toggle=async(source:HTTPSource,enabled:boolean)=>{await actions.saveSources(sources.map(item=>item.id===source.id?{...item,enabled}:item));};
  return <div className="page" data-testid="sources-page"><header className="page-header"><div><h1>数据源管理</h1><p>配置返回 IPv4 节点的 HTTP 文本或 JSON 地址；探测逻辑不依赖固定源。</p></div><div className="page-actions"><Button variant="primary" onPress={()=>{setError("");setEditing(blank())}}><Plus size={16}/>添加数据源</Button></div></header>
    <section className="panel source-list"><div className="section-heading"><h2>HTTP 数据源</h2><span>{sources.filter(item=>item.enabled).length} / {sources.length} 已启用</span></div>{sources.map(source=><div className="source-row" key={source.id}><div className="source-title"><span className="source-icon"><Database size={15}/></span><span><strong>{source.name}</strong><small>{source.enabled?"参与下一次测速":"已停用"}</small></span></div><div className="source-url" title={source.url}>{source.url}</div><div className="source-meta">{source.lastFetched?new Date(source.lastFetched).toLocaleString("zh-CN"):"从未获取"}</div><div className="source-meta">{source.lastStatus||"待检查"} · {source.nodeCount} 节点</div><div className="source-actions"><Switch aria-label={`${source.name} 启用状态`} isSelected={source.enabled} onChange={value=>void toggle(source,value)}><Switch.Content><Switch.Control><Switch.Thumb/></Switch.Control></Switch.Content></Switch><Button isIconOnly variant="tertiary" aria-label="编辑数据源" onPress={()=>{setError("");setEditing({...source})}}><Pencil size={14}/></Button><Button isIconOnly variant="tertiary" aria-label="删除数据源" onPress={()=>void remove(source.id)}><Trash2 size={14}/></Button></div></div>)}</section>
    {editing&&<Modal isOpen onOpenChange={open=>{if(!open)setEditing(undefined)}}><Modal.Trigger className="sr-only" aria-label="数据源编辑器"><span/></Modal.Trigger><Modal.Backdrop><Modal.Container size="md"><Modal.Dialog><Modal.Header><Modal.Heading>{editing.id?"编辑数据源":"添加数据源"}</Modal.Heading><Modal.CloseTrigger aria-label="关闭"><X size={17}/></Modal.CloseTrigger></Modal.Header><Modal.Body><div className="field"><label>名称</label><Input aria-label="数据源名称" value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})}/></div><div className="field"><label>HTTP URL</label><Input aria-label="数据源 URL" value={editing.url} onChange={event=>setEditing({...editing,url:event.target.value})}/><small>支持空白分隔文本、JSON 数组和嵌套对象；仅请求 identity 编码。</small></div>{error&&<p className="field-error">{error}</p>}</Modal.Body><Modal.Footer><Button variant="tertiary" onPress={()=>setEditing(undefined)}>取消</Button><Button variant="primary" onPress={()=>void save()}>保存</Button></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>}
  </div>;
}
